### ISSUE TITLE
Some datasets do not have donor information

### ISSUE THREAD

**Issue by bherr2** [hubmapconsortium/data-products-ui#41]
@mruffalo when using the kidney data products in h5ad format, I'm noticing empty values for age, sex, bmi, etc for some datasets. It seems to be from derived datasets? Is this data redundant? If not, can you fill in those blank values by looking up the donor data for them? It would be best if it were in the data product.

**Comment by mruffalo** [comment]
Thanks @bherr2 -- @pennycuda can you verify this for the data products that are loaded?

**Comment by bherr2** [comment]
You can test with this [notebook](https://github.com/hubmapconsortium/hra-hubmap-kpmp-integration/blob/main/notebooks/normalize-metadata.ipynb) (you'll also need to run the downloading notebooks to get the h5ad files), but I specifically test if age, sex, or race is not filled in and call out to the entity api to fill it in (see ~`add_hubmap_donor_info`)

**Comment by pennycuda** [comment]
Hi Bruce, I've determined this to be an inconsistency in the search API that I was using to grab patient data. Thanks for providing that very useful notebook! I think the entity API will be very helpful in fixing this.

**Comment by pennycuda** [comment]
@bherr2 hi again! With the code you provided, I was able to pull all additional donor information from the Entity API. I am rerunning all data products now and they should be up within a week or so. Again, thank you for bringing this to our attention, and thank you for that notebook!

**Comment by bherr2** [comment]
Great! Happy to help :-)
